name: ci

on: pull_request

jobs:

  lint-code:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2  
     - name: Lint
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub token
          path: "./src/*.py" # Glob pattern for files to lint
          fail: true # Fail the action if pylint errors are found
          pr-message: true # Send a PR message if pylint errors are found
